<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.

 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Tag manager</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The manager allows you to create and manage site tags.</p>

    <h2>Content:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">List of tags</a></li>
        <li><a href="<?= $url('form') ?>">Add / Edit tag form</a></li>
    </ul>
</article>